import type { Metadata } from "next";

import "@/styles/globals.css";

import { fonts } from "@/fonts";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Financeiro Inteligente",
  description: "Generated by create next app"
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

const fontVariables = fonts.map((font) => font.variable).join(" ");

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt-br">
      <body className={`${fontVariables} font-sans antialiased`}>
        <ClerkProvider>{children}</ClerkProvider>
      </body>
    </html>
  );
}
